<?php

use yii\helpers\ArrayHelper;
use yii\widgets\Pjax;
use kartik\grid\GridView;
use app\models\JobContainer;
use app\actioncontrols\ShippingInstructionActControl;

/* @var $this yii\web\View  */
/* @var $model app\models\CompanyProfile  */

Pjax::begin([
    'id' => 'pjax-ContainerServices',
    'enableReplaceState' => false,
    'linkSelector' => '#pjax-ContainerServices ul.pagination a, th a',
    'clientOptions' => [
        'pjax:success' => 'function(){alert(\"yo\")}',
    ],
]);

// generated by fredyns\suite\giiant\crud\providers\core\RelationProvider::relationGrid
$JobContainerActControl = new \app\actioncontrols\JobContainerActControl();

$addJobContainer = $JobContainerActControl->button('create',
    [
    'label' => 'New Container Rent',
    'urlOptions' => [
        'JobContainerForm' => ['containerDepo_id' => $model->id],
    ],
    ]);

echo '<div class=\"table-responsive\">';
echo GridView::widget([
    //'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getContainerServices(),
        'pagination' => [
            'pageSize' => 50,
            'pageParam' => 'page-containerservices',
        ],
        'sort' => [
            'defaultOrder' => [
                'id' => SORT_DESC,
            ],
        ],
        ]),
    'pager' => [
        'class' => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel' => 'Last'
    ],
    'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
    'headerRowOptions' => ['class' => 'x'],
    'columns' => [
        ['class' => 'kartik\grid\SerialColumn'],
        [
            'label' => 'Shipping Inst.',
            'attribute' => 'shippingInstructionNumber',
            'format' => 'html',
            'value' => function (JobContainer $model, $key, $index, $widget) {
                $siActControl = new ShippingInstructionActControl([
                    'model' => $model->shippingInstruction,
                ]);

                $shipperName = $model->subAttribute('shippingInstruction.shipper.name');
                $destinationName = $model->subAttribute('shippingInstruction.destination.name');
                $shippingName = $model->subAttribute('shippingInstruction.shipping.name');
                $pieces = ['SI <b>#'.$siActControl->linkTo.'</b>'];

                if ($shipperName) {
                    $pieces[] = '<i class="inline-label">from</i> '.$shipperName;
                }

                if ($destinationName) {
                    $pieces[] = '<i class="inline-label">to</i> '.$destinationName;
                }

                if ($shippingName) {
                    $pieces[] = '<i class="inline-label">with</i> '.$shippingName;
                }

                return implode(' &nbsp;', $pieces);
            },
            'group' => true, // enable grouping,
            'groupedRow' => true, // move grouped column to a single grouped row
            'groupOddCssClass' => 'kv-grouped-row', // configure odd group cell css class
            'groupEvenCssClass' => 'kv-grouped-row', // configure even group cell css class
        ],
        [
            'label' => 'Date',
            'attribute' => 'stuffingDate',
            'options' => [
                'width' => '60px',
            ],
            'value' => function ($model) {
                $date = new \Datetime($model->stuffingDate);

                return ($date) ? $date->format('d M') : '-';
            },
        ],
        [
            'label' => 'Cont. Number',
            'class' => 'fredyns\suite\grid\KartikViewColumn',
            'actionControl' => 'app\actioncontrols\JobContainerActControl',
            'attribute' => 'containerNumber',
            'options' => [
                'width' => '120px',
            ],
        ],
        [
            'attribute' => 'size',
            'value' => function ($model) {
                return $model->size ? $model->sizeLabel : '-';
            },
        ],
        [
            'attribute' => 'type_id',
            'value' => function ($model) {
                return ArrayHelper::getValue($model, 'type.name', '-');
            },
        ],
        [
            'class' => 'fredyns\suite\grid\KartikActionColumn',
            'actionControl' => 'app\actioncontrols\JobContainerActControl',
        ],
    ],
    'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
    'headerRowOptions' => ['class' => 'kartik-sheet-style'],
    'filterRowOptions' => ['class' => 'kartik-sheet-style'],
    'pjax' => false, // pjax is set to always true for this demo
    'toolbar' => [
        $addJobContainer.' {export}',
    ],
    'export' => [
        'icon' => 'export',
        'label' => 'Export',
    ],
    'bordered' => true,
    'striped' => true,
    'condensed' => true,
    'responsive' => true,
    'hover' => true,
    'showPageSummary' => true,
    'pageSummaryRowOptions' => [
        'class' => 'kv-page-summary',
        'style' => 'height: 100px;'
    ],
    'persistResize' => false,
    'exportConfig' => [
        GridView::EXCEL => [
            'label' => 'Save as EXCEL',
            'filename' => $this->title.' - ContainerServices',
        ],
        GridView::PDF => [
            'label' => 'Save as PDF',
            'filename' => $this->title.' - ContainerServices',
        ],
    ],
    'panel' => [
        'type' => GridView::TYPE_PRIMARY,
        'heading' => false,
    ],
    'panelBeforeTemplate' => '
            <div class="clearfix">{summary}</div>
            <div class="pull-right">
                <div class="btn-toolbar kv-grid-toolbar" role="toolbar">
                    {toolbar}
                </div>
            </div>
            <div class="pull-left">
                <div class="kv-panel-pager">
                    {pager}
                </div>
            </div>
            {before}
            <div class="clearfix"></div>
        ',
]);
echo '</div>';

Pjax::end();
