<?php

use yii\helpers\Html;
use yii\helpers\Url;
use kartik\grid\GridView;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\ShippingInstructionSearch $searchModel
 */

$this->title = Yii::t('app', 'Shipping Instructions');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="giiant-crud shipping-instruction-index">

    <h1>
        <?= Yii::t('app', 'Shipping Instructions') ?>
        <small class="badge">
            List
        </small>
    </h1>

    <?php //echo $this->render('_search', ['model' =>$searchModel]);?>

    <?php
    \yii\widgets\Pjax::begin([
        'id' => 'pjax-main',
        'enableReplaceState' => false,
        'linkSelector' => '#pjax-main ul.pagination a, th a',
        'clientOptions' => [
            'pjax:success' => 'function(){alert(\"yo\")}',
        ],
    ]);
    ?>

    <div class="table-responsive">
        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'pager' => [
                'class' => yii\widgets\LinkPager::className(),
                'firstPageLabel' => 'First',
                'lastPageLabel' => 'Last',
            ],
            'filterModel' => $searchModel,
            'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
            'headerRowOptions' => ['class' => 'x'],
            'columns' => [
                ['class' => 'kartik\grid\SerialColumn'],
                [
                    'class' => 'fredyns\suite\grid\KartikViewColumn',
                    'actionControl' => 'app\actioncontrols\ShippingInstructionActControl',
                    'attribute' => 'number',
                ],
                // generated by fredyns\suite\giiant\crud\providers\core\RelationProvider::columnFormat
                [
                    'attribute' => 'shipper_id',
                    'options' => [],
                    'format' => 'raw',
                    'value' => function ($model) {
                        return \fredyns\suite\widgets\LinkedDetail::widget([
                            'model' => $model,
                            'attribute' => 'shipper',
                            'actionControl' => 'app\actioncontrols\CompanyProfileActControl',
                        ]);
                    },
                ],
                // generated by fredyns\suite\giiant\crud\providers\core\RelationProvider::columnFormat
                [
                    'attribute' => 'shipping_id',
                    'options' => [],
                    'format' => 'raw',
                    'value' => function ($model) {
                        return \fredyns\suite\widgets\LinkedDetail::widget([
                            'model' => $model,
                            'attribute' => 'shipping',
                            'actionControl' => 'app\actioncontrols\ShippingActControl',
                        ]);
                    },
                ],
                // generated by fredyns\suite\giiant\crud\providers\core\RelationProvider::columnFormat
                [
                    'attribute' => 'destination_id',
                    'options' => [],
                    'format' => 'raw',
                    'value' => function ($model) {
                        return \fredyns\suite\widgets\LinkedDetail::widget([
                            'model' => $model,
                            'attribute' => 'destination',
                            'actionControl' => 'app\actioncontrols\ContainerPortActControl',
                        ]);
                    },
                ],
                [
                    'class' => 'fredyns\suite\grid\KartikActionColumn',
                    'actionControl' => 'app\actioncontrols\ShippingInstructionActControl',
                ],
            ],
            'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
            'headerRowOptions' => ['class' => 'kartik-sheet-style'],
            'filterRowOptions' => ['class' => 'kartik-sheet-style'],
            'pjax' => false, // pjax is set to always true for this demo
            'toolbar' => [
                $actionControl->button('create').' {export}',
            ],
            'export' => [
                'icon' => 'export',
                'label' => 'Export',
            ],
            'bordered' => true,
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'hover' => true,
            'showPageSummary' => true,
            'pageSummaryRowOptions' => [
                'class' => 'kv-page-summary',
                'style' => 'height: 100px;'
            ],
            'persistResize' => false,
            'exportConfig' => [
                GridView::EXCEL => [
                    'label' => 'Save as EXCEL',
                    'filename' => 'Shipping Instructions',
                ],
                GridView::PDF => [
                    'label' => 'Save as PDF',
                    'filename' => 'Shipping Instructions',
                ],
            ],
            'panel' => [
                'type' => GridView::TYPE_PRIMARY,
            ],
            'panelBeforeTemplate' => '
                <div class="pull-right">
                    <div class="btn-toolbar kv-grid-toolbar" role="toolbar">
                        {toolbar}
                    </div>
                </div>
                <div class="pull-left">
                    <div class="kv-panel-pager">
                        {pager}
                    </div>
                </div>
                {before}
                <div class="clearfix"></div>
            ',
        ]);
        ?>

    </div>

    <?php \yii\widgets\Pjax::end(); ?>

</div>
