<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use cornernote\returnurl\ReturnUrl;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\JobContainer $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="job-container-form">

    <?php
    $form = ActiveForm::begin([
        'id' => 'JobContainer',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]);
    
    echo Html::hiddenInput('ru', ReturnUrl::getRequestToken());
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>

            <!-- attribute shippingInstruction_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'shippingInstruction_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\ShippingInstruction::find()->all(), 'id', 'id'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['shippingInstruction_id'])),
                ]
            );
            ?>

            <!-- attribute stuffingLocation_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'stuffingLocation_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\StuffingLocation::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['stuffingLocation_id'])),
                ]
            );
            ?>

            <!-- attribute driver_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'driver_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\Profile::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['driver_id'])),
                ]
            );
            ?>

            <!-- attribute supervisor_id -->
            <?=
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'supervisor_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\TruckSupervisor::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['supervisor_id'])),
                ]
            );
            ?>

            <!-- attribute stuffingDate -->
            <?=
            // generated by fredyns\suite\giiant\crud\providers\extensions\DateProvider::activeField
            $form
                ->field($model, 'stuffingDate')
                // TODO: must configured properly together with model
                //->widget(\yii\jui\DatePicker::classname(),
                //    [
                //        'dateFormat' => 'yyyy-MM-dd',
                //    ])
            ?>

            <!-- attribute containerNumber -->
            <?=
            $form->field($model, 'containerNumber')->textInput(['maxlength' => true])
            ?>

            <!-- attribute sealNumber -->
            <?=
            $form->field($model, 'sealNumber')->textInput(['maxlength' => true])
            ?>
        </p>

        <?php $this->endBlock(); ?>
        
        <?=
        Tabs::widget([
            'encodeLabels' => false,
            'items' => [
                [
                    'label'   => Yii::t('app', 'JobContainer'),
                    'content' => $this->blocks['main'],
                    'active'  => true,
                ],
            ],
        ]);
        ?>

        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-' . $model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

