<?php

use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\helpers\Url;
use cornernote\returnurl\ReturnUrl;
use dmstr\bootstrap\Tabs;
use fredyns\suite\helpers\ActiveUser;
use fredyns\suite\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View  */
/* @var $model app\models\CompanyProfile  */

$copyParams = $model->attributes;

$this->title = $actionControl->breadcrumbLabel('index')." "
    .$actionControl->breadcrumbLabel('view');

$this->params['breadcrumbs'][] = $actionControl->breadcrumbItem('index');
$this->params['breadcrumbs'][] = $actionControl->breadcrumbLabel('view');
?>
<div class="giiant-crud company-profile-view">

    <h1>
        <?= Yii::t('app', 'Company Profile') ?>
        <small>
            <?= $model->name ?>
            <?php if ($model->recordStatus == 'deleted'): ?>
                <span class="badge">deleted</span>
            <?php endif; ?>
        </small>
    </h1>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= $actionControl->buttons(['index', 'create']); ?>
        </div>

        <div class="pull-right">
            <?= $actionControl->buttons(['update', 'delete', 'restore']); ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('app\models\CompanyProfile'); ?>
    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            [
                'attribute' => 'companyType.name',
                'label' => 'Type',
            ],
            'address:ntext',
            'phone',
            'email',
            'npwp',
        ],
    ]);
    ?>

    <?php $this->endBlock(); ?>

    <?php $this->beginBlock('Personels'); ?>

    <?php
    Pjax::begin([
        'id' => 'pjax-Personels',
        'enableReplaceState' => false,
        'linkSelector' => '#pjax-Personels ul.pagination a, th a',
        'clientOptions' => [
            'pjax:success' => 'function(){alert(\"yo\")}',
        ],
    ]);

    // generated by fredyns\suite\giiant\crud\providers\core\RelationProvider::relationGrid
    $PersonelActControl = new \app\actioncontrols\PersonelActControl;

    $addPersonel = $PersonelActControl->button('create',
        [
        'label' => 'New Personel',
        'urlOptions' => [
            'PersonelForm' => ['companyProfile_id' => $model->id],
        ],
    ]);

    echo '<div class=\"table-responsive\">';
    echo GridView::widget([
        //'layout' => '{summary}{pager}<br/>{items}{pager}',
        'dataProvider' => new \yii\data\ActiveDataProvider([
            'query' => $model->getPersonels(),
            'pagination' => [
                'pageSize' => 50,
                'pageParam' => 'page-personels',
            ]
            ]),
        'pager' => [
            'class' => yii\widgets\LinkPager::className(),
            'firstPageLabel' => 'First',
            'lastPageLabel' => 'Last'
        ],
        'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
        'headerRowOptions' => ['class' => 'x'],
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],
            // generated by fredyns\suite\giiant\crud\providers\core\RelationProvider::columnFormat
            [
                'attribute' => 'profile_id',
                'options' => [],
                'format' => 'raw',
                'value' => function ($model) {
                    return \fredyns\suite\widgets\LinkedDetail::widget([
                            'model' => $model,
                            'attribute' => 'profile',
                            'actionControl' => 'app\actioncontrols\ProfileActControl',
                    ]);
                },
            ],
            'title',
            // generated by fredyns\suite\giiant\crud\providers\core\RelationProvider::relationGrid
            [
                'class' => 'fredyns\suite\grid\KartikActionColumn',
                'actionControl' => 'app\actioncontrols\PersonelActControl',
            ],
        ],
        'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'pjax' => false, // pjax is set to always true for this demo
        'toolbar' => [
            $addPersonel.' {export}',
        ],
        'export' => [
            'icon' => 'export',
            'label' => 'Export',
        ],
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'showPageSummary' => true,
        'pageSummaryRowOptions' => [
            'class' => 'kv-page-summary',
            'style' => 'height: 100px;'
        ],
        'persistResize' => false,
        'exportConfig' => [
            GridView::EXCEL => [
                'label' => 'Save as EXCEL',
                'filename' => $this->title.' - Personel',
            ],
            GridView::PDF => [
                'label' => 'Save as PDF',
                'filename' => $this->title.' - Personel',
            ],
        ],
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => false,
        ],
        'panelBeforeTemplate' => '
            <div class="clearfix">{summary}</div>
            <div class="pull-right">
                <div class="btn-toolbar kv-grid-toolbar" role="toolbar">
                    {toolbar}
                </div>
            </div>
            <div class="pull-left">
                <div class="kv-panel-pager">
                    {pager}
                </div>
            </div>
            {before}
            <div class="clearfix"></div>
        ',
    ]);
    echo '</div>';

    Pjax::end();
    ?>

    <?php $this->endBlock(); ?>

    <?php $this->beginBlock('SiServices'); ?>
    <?= $this->render('view/si-services', ['model' => $model]); ?>
    <?php $this->endBlock(); ?>

    <?php $this->beginBlock('SiOrders'); ?>
    <?= $this->render('view/si-orders', ['model' => $model]); ?>
    <?php $this->endBlock(); ?>

    <?php $this->beginBlock('ContainerServices'); ?>
    <?= $this->render('view/container-services', ['model' => $model]); ?>
    <?php $this->endBlock(); ?>

    <?php $this->beginBlock('TruckServices'); ?>
    <?= $this->render('view/truck-services', ['model' => $model]); ?>
    <?php $this->endBlock(); ?>

    <?php $this->beginBlock('info'); ?>
    <?=
    DetailView::widget([
        'model' => $model,
        'profileActControl' => 'app\actioncontrols\ProfileActControl',
        'attributes' => [
            [
                'attribute' => 'recordStatus',
                'format' => 'html',
                'value' => '<span class="badge">'.$model->recordStatus.'</span>',
            ],
            [
                'label' => 'Created',
                'blamed' => 'createdBy',
                'timestamp' => 'created_at',
            ],
            [
                'label' => 'Updated',
                'blamed' => 'updatedBy',
                'timestamp' => 'updated_at',
            ],
            [
                'label' => 'Deleted',
                'blamed' => 'deletedBy',
                'timestamp' => 'deleted_at',
            ],
        ],
    ]);
    ?>
    <?php $this->endBlock(); ?>

    <?=
    Tabs::widget([
        'id' => 'relation-tabs',
        'encodeLabels' => false,
        'items' => [
            [
                'label' => '<b class=""># '.$model->id.'</b>',
                'content' => $this->blocks['app\models\CompanyProfile'],
                'active' => true,
            ],
            [
                'content' => $this->blocks['Personels'],
                'label' => '<small>Personels <span class="badge badge-default">'
                .$model->getPersonels()->count()
                .'</span></small>',
                'active' => false,
            ],
            [
                'content' => $this->blocks['SiServices'],
                'label' => '<small>SI Services <span class="badge badge-default">'
                .$model->getSiServices()->count()
                .'</span></small>',
                'active' => false,
                'visible' => $model->showSiServices,
            ],
            [
                'content' => $this->blocks['SiOrders'],
                'label' => '<small>SI Orders <span class="badge badge-default">'
                .$model->getSiOrders()->count()
                .'</span></small>',
                'active' => false,
                'visible' => $model->showSiOrders,
            ],
            [
                'content' => $this->blocks['ContainerServices'],
                'label' => '<small>Container Service <span class="badge badge-default">'
                .$model->getContainerServices()->count()
                .'</span></small>',
                'active' => false,
                'visible' => $model->showContainerServices,
            ],
            [
                'content' => $this->blocks['TruckServices'],
                'label' => '<small>Trucking Services <span class="badge badge-default">'
                .$model->getTruckServices()->count()
                .'</span></small>',
                'active' => false,
                'visible' => $model->showTruckServices,
            ],
            [
                'content' => $this->blocks['info'],
                'label' => '<small>info</small>',
                'active' => false,
                'visible' => ActiveUser::isAdmin(),
            ],
        ],
    ]);
    ?>

</div>
