<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Booking Request' => '',
    'Branches' => '@@Kantor Cabang@@',
    'Chart' => '',
    'Company' => 'Perusahaan',
    'Company Profile' => 'Daftar Perusahaan',
    'Company Profiles' => 'Daftar Perusahaan',
    'Company Type' => '',
    'Company Types' => '',
    'CompanyType' => '',
    'Container Depo' => '',
    'Container Port' => 'Pelabuhan',
    'Container Ports' => 'Pelabuhan',
    'Container Type' => '',
    'Container Types' => '',
    'ContainerType' => '',
    'Depo' => '',
    'Homepage' => '',
    'Job Container' => 'Container',
    'Job Containers' => 'Container',
    'Main Menu' => '@@Menu Utama@@',
    'Mandor' => 'Mandor/Driver',
    'New Container' => 'Container Baru',
    'Office Branches' => '',
    'Other' => '@@Lainnya@@',
    'Pages' => 'Halaman',
    'Personel' => 'Personil',
    'Personels' => 'Personil',
    'Profile' => 'Profil',
    'Profiles' => 'Profil',
    'Search' => 'Pencarian',
    'Search Container' => '@@Pencarian Container@@',
    'Search Containers' => 'Pencarian Container',
    'Search DO' => '',
    'Search Result' => 'Hasil Pencarian',
    'Shipper' => '',
    'Shippers' => '',
    'Shipping' => 'Shipping',
    'Shipping Instruction' => 'SI',
    'Shipping Instructions' => 'SI',
    'Shippings' => 'Shipping',
    'Stuffing Location' => 'Lokasi Stuffing',
    'Stuffing Locations' => 'Lokasi Stuffing',
    'Summary Cargo' => '',
    'Truck Supervisor' => '@@Mandor/Driver@@',
    'Truck Supervisors' => '@@Mandor/Driver@@',
    'Truck Vendor' => '',
    'Truck Vendors' => '',
    '____' => '@@____@@',
];
