
CREATE TABLE IF NOT EXISTS `companyType` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `companyProfile`
ADD COLUMN `companyType_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `name`;
