-- MySQL Workbench Synchronization
-- Generated: 2017-02-22 19:01
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Fredy

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `daily_log` (
  `date` DATE NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`date`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `monthly_log` (
  `month` DATE NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`month`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `daily_shipper` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `shipper_id` INT(10) UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `monthly_shipper` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `shipper_id` INT(10) UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `monthly_destination` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `destination_id` INT(10) UNSIGNED NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `daily_driving` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `driver_id` INT(10) UNSIGNED NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  `kilometerage` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'in kilometers',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `daily_truckSupervising` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `supervisor_id` INT(10) UNSIGNED NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `monthly_driving` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `driver_id` INT(10) UNSIGNED NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  `kilometerage` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'in kilometers',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `monthly_truckSupervising` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `supervisor_id` INT(10) UNSIGNED NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `daily_stuffingLocation` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `stuffingLocation_id` INT(10) UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `monthly_stuffingLocation` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `stuffingLocation_id` INT(10) UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `containerQty` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
