<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "daily_shipper".
 *
 * @property integer $id
 * @property integer $shipper_id
 * @property string $date
 * @property integer $containerQty
 *
 * @property \app\models\CompanyProfile $shipper
 * @property string $aliasModel
 */
abstract class DailyShipper extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'daily_shipper';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shipper_id', 'date'], 'required'],
            [['shipper_id', 'containerQty'], 'integer'],
            [['date'], 'safe'],
            [['shipper_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CompanyProfile::className(), 'targetAttribute' => ['shipper_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'shipper_id' => 'Shipper',
            'date' => 'Date',
            'containerQty' => 'Container Qty',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShipper()
    {
        return $this->hasOne(\app\models\CompanyProfile::className(), ['id' => 'shipper_id']);
    }
                
}
