<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "daily_driving".
 *
 * @property integer $id
 * @property integer $driver_id
 * @property integer $containerQty
 * @property integer $kilometerage
 *
 * @property \app\models\CompanyProfile $driver
 * @property string $aliasModel
 */
abstract class DailyDriving extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'daily_driving';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['driver_id'], 'required'],
            [['driver_id', 'containerQty', 'kilometerage'], 'integer'],
            [['driver_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CompanyProfile::className(), 'targetAttribute' => ['driver_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'driver_id' => 'Driver',
            'containerQty' => 'Container Qty',
            'kilometerage' => 'Kilometerage',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDriver()
    {
        return $this->hasOne(\app\models\CompanyProfile::className(), ['id' => 'driver_id']);
    }
                
}
