<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "jobContainer".
 *
 * @property integer $id
 * @property integer $shippingInstruction_id
 * @property string $containerNumber
 * @property string $sealNumber
 * @property string $stuffingDate
 * @property integer $stuffingLocation_id
 * @property integer $driver_id
 * @property integer $supervisor_id
 * @property string $worknote
 * @property string $recordStatus
 * @property integer $deleted_at
 * @property integer $deleted_by
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\ShippingInstruction $shippingInstruction
 * @property \app\models\StuffingLocation $stuffingLocation
 * @property \app\models\Profile $driver
 * @property \app\models\TruckSupervisor $supervisor
 * @property string $aliasModel
 */
abstract class JobContainer extends \yii\db\ActiveRecord
{
    
    /**
     * ENUM field values
     */
    const RECORDSTATUS_ACTIVE = 'active';
    const RECORDSTATUS_DELETED = 'deleted';

    var $enum_labels = false;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jobContainer';
    }
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'blameable' => [
                'class' => BlameableBehavior::className(),
            ],
            'timestamp' => [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shippingInstruction_id', 'stuffingLocation_id', 'driver_id', 'supervisor_id', 'deleted_at', 'deleted_by'], 'integer'],
            [['stuffingDate'], 'safe'],
            [['worknote', 'recordStatus'], 'string'],
            [['containerNumber'], 'string', 'max' => 32],
            [['sealNumber'], 'string', 'max' => 64],
            [['shippingInstruction_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ShippingInstruction::className(), 'targetAttribute' => ['shippingInstruction_id' => 'id']],
            [['stuffingLocation_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StuffingLocation::className(), 'targetAttribute' => ['stuffingLocation_id' => 'id']],
            [['driver_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Profile::className(), 'targetAttribute' => ['driver_id' => 'id']],
            [['supervisor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TruckSupervisor::className(), 'targetAttribute' => ['supervisor_id' => 'id']],
            ['recordStatus', 'in', 'range' => [
                    self::RECORDSTATUS_ACTIVE,
                    self::RECORDSTATUS_DELETED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'shippingInstruction_id' => 'Shipping Instruction',
            'containerNumber' => 'Container Number',
            'sealNumber' => 'Seal Number',
            'stuffingDate' => 'Stuffing Date',
            'stuffingLocation_id' => 'Stuffing Location',
            'driver_id' => 'Driver',
            'supervisor_id' => 'Supervisor',
            'worknote' => 'Worknote',
            'recordStatus' => 'Record Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'deleted_at' => 'Deleted At',
            'deleted_by' => 'Deleted By',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShippingInstruction()
    {
        return $this->hasOne(\app\models\ShippingInstruction::className(), ['id' => 'shippingInstruction_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStuffingLocation()
    {
        return $this->hasOne(\app\models\StuffingLocation::className(), ['id' => 'stuffingLocation_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDriver()
    {
        return $this->hasOne(\app\models\Profile::className(), ['id' => 'driver_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSupervisor()
    {
        return $this->hasOne(\app\models\TruckSupervisor::className(), ['id' => 'supervisor_id']);
    }
                
    /**
     * get column recordStatus enum value label
     * @param string $value
     * @return string
     */
    public static function getRecordStatusValueLabel($value)
    {
        $labels = self::optsRecordStatus();

        if(isset($labels[$value])) {
            return $labels[$value];
        }

        return $value;
    }

    /**
     * column recordStatus ENUM value labels
     * @return array
     */
    public static function optsRecordStatus()
    {
        return [
            self::RECORDSTATUS_ACTIVE => self::RECORDSTATUS_ACTIVE,
            self::RECORDSTATUS_DELETED => self::RECORDSTATUS_DELETED,
        ];
    }
    
}
