<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "monthly_truckSupervising".
 *
 * @property integer $id
 * @property integer $supervisor_id
 * @property integer $containerQty
 *
 * @property \app\models\TruckSupervisor $supervisor
 * @property string $aliasModel
 */
abstract class MonthlyTruckSupervising extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'monthly_truckSupervising';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['supervisor_id'], 'required'],
            [['supervisor_id', 'containerQty'], 'integer'],
            [['supervisor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TruckSupervisor::className(), 'targetAttribute' => ['supervisor_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'supervisor_id' => 'Supervisor',
            'containerQty' => 'Container Qty',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSupervisor()
    {
        return $this->hasOne(\app\models\TruckSupervisor::className(), ['id' => 'supervisor_id']);
    }
                
}
