<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "monthly_destination".
 *
 * @property integer $id
 * @property integer $destination_id
 * @property integer $containerQty
 *
 * @property \app\models\ContainerPort $destination
 * @property string $aliasModel
 */
abstract class MonthlyDestination extends \yii\db\ActiveRecord
{
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'monthly_destination';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['destination_id'], 'required'],
            [['destination_id', 'containerQty'], 'integer'],
            [['destination_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ContainerPort::className(), 'targetAttribute' => ['destination_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'destination_id' => 'Destination',
            'containerQty' => 'Container Qty',
        ];
    }
        
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDestination()
    {
        return $this->hasOne(\app\models\ContainerPort::className(), ['id' => 'destination_id']);
    }
                
}
